---
# Credentials
user: auto763e90_sync_4901a
member: auto763e90_sync_4913
password: QWFAMTIzNDU=

api:
  oauth2: https://oauth2-api-4qc-nolimit.k8s.flostage.com
  v4: https://v41-api-qc-nolimit.k8s.flostage.com
  sabredav: https://dav.k8s.flostage.com
  web: https://flo.k8s.flostage.com

platforms:
  web:
    browser: chrome
    url: https://flo.k8s.flostage.com
  mac:
    bundle_id: com.floware.flomac
    appium: 4727
    system: 10101
  iphone:
    device_uid: F459908A-AA78-44FB-9C9F-CAE732B04C03
    bundle_id: com.floware.flo.staging
    appium: 4725
    wda: 8102
  ipad:
    device_uid: 504C29BB-5554-4F5A-8B26-D232D6294B3B
    bundle_id: com.floware.universalflo.staging
    appium: 4725
    wda: 8102

smtp_host: smtp.flostage.com
smtp_port: 465
imap_host: imap.flostage.com
imap_port: 993

# App secret key
alias: Y2JhZDk0NDQyNDM5M2NmMzA5ZWZhZjBlNzBmMWIxMjU=
app_id: ZTcwZjFiMTI1Y2JhZDk0NDQyNDM5M2NmMzA5ZWZhZjA=
