---
urls:
  oauth2: https://oauth2-api-4qc-nolimit.k8s.flostage.com
  v4: https://v41-api-qc-nolimit.k8s.flostage.com
  sabredav: https://dav.k8s.flostage.com
  #  web: https://flo.k8s.flostage.com
  web: https://www.google.com/
smtp_host: smtp.flostage.com
smtp_port: 465
imap_host: imap.flostage.com
imap_port: 993
yahoo_box_name: Mailbox Yahoo
yahoo_mail: team_automation@yahoo.com
yahoo_password: eGd0aG9pd2t1dmhqa3B5eg==

# Credentials
user: auto763e90_sync_4901a@flostage.com
member: auto763e90_sync_4913@flostage.com
password: QWFAMTIzNDU=

platforms:
  iphone: F459908A-AA78-44FB-9C9F-CAE732B04C03
  ipad: 504C29BB-5554-4F5A-8B26-D232D6294B3B
  mac: com.floware.flomac.internal
  web: chrome

# App secret key
alias: Y2JhZDk0NDQyNDM5M2NmMzA5ZWZhZjBlNzBmMWIxMjU=
app_id: ZTcwZjFiMTI1Y2JhZDk0NDQyNDM5M2NmMzA5ZWZhZjA=
